<img src="./logo.png" width="256px" />

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In this tutorial, I cover the most useful functions provided by NumPy for numerical and mathematical operations.

First, we can import the **numpy** package as follows:

In [1]:
import numpy as np
import sys
import time

np.random.seed(313)

# Part I: Introduction

---

## Why NumPy Arrays?

NumPy are preferred to tradition Python arrays/lists for three reasons:

1. Less Memory Usage
2. Faster Computation/Runtime
3. Convenience

**I. Less Memory Usage**

In [2]:
lst = range(1000)
print(sys.getsizeof(1) * len(lst))

28000


In [3]:
arr = np.arange(1000)
print(arr.size * arr.itemsize)

8000


**II. Faster Computation**

NumPy arrays are faster than python lists, in terms of mathematical operations.

In [4]:
SIZE = 100000

lst_1 = range(SIZE)
lst_2 = range(SIZE)

arr_1 = np.arange(SIZE)
arr_2 = np.arange(SIZE)

start_time = time.time()
res = [(x + y) for x, y in zip(lst_1, lst_2)]
print("Python list took: ", (time.time() - start_time) * 1000)

start_time = time.time()
res = arr_1 + arr_2
print("Numpy array took: ", (time.time() - start_time) * 1000)

Python list took:  9.765386581420898
Numpy array took:  1.7216205596923828


**III. Convenience**

It is easy to do mathematical operations on NumPy arrays, as below:

In [5]:
arr_1, arr_2 = np.array([1, 2, 3]), np.array([4, 5, 6])

In [6]:
print('Element-wise Sum: {}, Sub: {}, Mul: {}.'.format(arr_1 + arr_2, 
                                                       arr_1 - arr_2, 
                                                       arr_1 * arr_2))

Element-wise Sum: [5 7 9], Sub: [-3 -3 -3], Mul: [ 4 10 18].


---

## Generating NumPy Arrays

### 1. From Python List

It is possible to create NumPy arrays from typical python arrays, as follows:

In [7]:
arr_1d = np.asarray([2, 3, 6, 1, 5])
arr_2d = np.asarray([[4, 5, 6], [2, 0, 8]], dtype=np.float16)

print('The 1D array: {} \n'.format(arr_1d))
print('The 2D array:\n {}'.format(arr_2d))

The 1D array: [2 3 6 1 5] 

The 2D array:
 [[4. 5. 6.]
 [2. 0. 8.]]


### 2. Zeros and Ones

We can generate arrays of ones and zeros as below:

In [8]:
ones = np.ones((2, 10))
zeros = np.zeros((2, 10))

print(ones)
print(zeros)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 3. Range

To create a NumPy array from a range, we do:

In [9]:
arr = np.arange(10, 25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

### 4. linspace

It returns evenly spaced numbers over a specified interval.

**Signature**

`np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)`

Please note that the stopping point is not included.

In [10]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [11]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### 5. eye

The **eye** function returns an identity matrix, i.e., a 2-D array where elements on the diagonal are equal to 1.

**Signature**

`np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')`

**Parameters**

* N: int - Number of rows in the output.
* M: int, optional - Number of columns in the output. If None, defaults to `N`.
* k: int, optional - Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.eye(N=4, M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(N=4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### 6. Random Functions

The `np.random` let us generate arrays of random numbers. The most popular random functions are:

* **random()**: It returns a random number from the interval `[0.0, 1.0)`.
    
* **rand(d0, d1, ..., dn):** It generates an array, with a dimension of (d0, d1, ..., dn), which is "uniformly" filled by random numbers.

* **randn(d0, d1, ..., dn):** It generates an array, with a dimension of (d0, d1, ..., dn), filled by random numbers from the "standard" normal distribution.

* **randint(low, high=None, size=None, dtype='l'):** It generates an array, with a dimension of (d0, d1, ..., dn), which is filled by random integers from the interval of `[low, high)`.

In [15]:
np.random.random()

0.1655396242835081

In [16]:
# uniform distribution
np.random.rand(3, 4)

array([[0.55010437, 0.8608718 , 0.61793372, 0.94624639],
       [0.56085797, 0.86958749, 0.17240047, 0.45221703],
       [0.52613267, 0.43633415, 0.78297911, 0.5921082 ]])

In [17]:
# normal distribution, with a zero mean
np.random.randn(3, 4)

array([[ 0.79920493, -0.45609488,  0.04940156, -0.74214685],
       [-1.09281066,  2.30604849, -1.51152898, -0.84547472],
       [ 0.42579229, -1.16183798,  0.13640745,  1.50104789]])

In [18]:
np.random.randint(0, 100, (3, 4))

array([[87, 62, 27, 35],
       [78, 53, 84, 37],
       [22, 70, 27, 84]])

---

## NumPy Array Functions

There are some functions or features associated with arrays in NumPy:

1. **min()** and **max()** return the minimum and maximum numbers in NumPy arrays.
2. **argmin()** and **argmax()** return the index of minimum and maximum numbers in NumPy arrays.
3. **shape** returns the shape of an array.
4. **dtype** returns the data type of an array.
5. **reshape(n, m)** reshapes an array with a new dimension of (n, m).

In [19]:
arr = np.random.randint(0, 100, (4, 9))
arr

array([[88, 82,  6, 42, 51, 28, 92, 66, 80],
       [ 3, 42, 73, 19, 56, 44, 43, 61, 60],
       [63, 28, 34, 81, 91, 44, 59, 23, 94],
       [26, 86, 47,  1, 13, 58, 51, 53, 66]])

In [20]:
print('The min and max numbers are {} and {}, respectively.'.format(arr.min(), arr.max()))

The min and max numbers are 1 and 94, respectively.


In [21]:
print('The index of min and max numbers are {} and {}, respectively.'.format(arr.argmin(), arr.argmax()))

The index of min and max numbers are 30 and 26, respectively.


In [22]:
print('The shape of array is {}, and the data type of array is {}.'.format(arr.shape, arr.dtype))

The shape of array is (4, 9), and the data type of array is int64.


In [23]:
arr = arr.reshape(3, 12)
arr

array([[88, 82,  6, 42, 51, 28, 92, 66, 80,  3, 42, 73],
       [19, 56, 44, 43, 61, 60, 63, 28, 34, 81, 91, 44],
       [59, 23, 94, 26, 86, 47,  1, 13, 58, 51, 53, 66]])

---

## Indexing and Slicing of NumPy Arrays

### 1. Indexing and Slicing of 1D Arrays

Let's create a typical Python and a NumPy array:

In [24]:
lst = list(range(0, 10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
print(arr[...])

[0 1 2 3 4 5 6 7 8 9]


Retrieving all elements of a list by `...`, e.g., `lst[...]`, is not possible.

In [27]:
print('{} vs. {}'.format(lst[5], arr[5]))

5 vs. 5


In [28]:
print('{} vs. {}'.format(lst[1:5], arr[1:5]))

[1, 2, 3, 4] vs. [1 2 3 4]


In [29]:
print('{} vs. {}'.format(lst[5:], arr[5:]))

[5, 6, 7, 8, 9] vs. [5 6 7 8 9]


### 2. Slicing and Broadcasting

For the python lists, `arr[0:5] = 100` is not possible! On the other, we can do it with an NumPy array.

In [30]:
arr = np.arange(0, 10)

In [31]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [32]:
sliced = arr[5:7]
sliced

array([5, 6])

Note that if we change the elements of the sliced array, the elements of the original array are also changed.

In [33]:
sliced[:] = 80
sliced

array([80, 80])

In [34]:
arr

array([100, 100, 100, 100, 100,  80,  80,   7,   8,   9])

To bypass this case, we can usem the `copy` function:

In [35]:
arr_copy = arr.copy()[:2]
arr_copy

array([100, 100])

In [36]:
arr_copy[:] = 75
arr_copy

array([75, 75])

We have no change in the original array:

In [37]:
arr

array([100, 100, 100, 100, 100,  80,  80,   7,   8,   9])

### 3. Indexing and Slicing of 2D Arrays

Let's create a 2D array, i.e., a matrix, as follows:

In [38]:
mat = np.random.rand(3, 4)
mat

array([[0.17682077, 0.38666533, 0.73258622, 0.42644438],
       [0.54252846, 0.62054132, 0.56371885, 0.97001606],
       [0.84377151, 0.87853951, 0.54671285, 0.35772691]])

Elements can be retrieved by either single or double brucket(s) notations. However, the **single brucket** notation is recommended.

In [39]:
print('{} and {}'.format(mat[0, 2], mat[0][2]))

0.7325862165956133 and 0.7325862165956133


A matrix can be sliced as follows:

In [40]:
mat[:, 0:2]

array([[0.17682077, 0.38666533],
       [0.54252846, 0.62054132],
       [0.84377151, 0.87853951]])

Double brucket notation does not work for slicing a matrix. For instance, in the following example `mat[:][0:2]` is equal to `mat[0:2]`. So, the result is not what we want.

In [41]:
mat[:][0:2]

array([[0.17682077, 0.38666533, 0.73258622, 0.42644438],
       [0.54252846, 0.62054132, 0.56371885, 0.97001606]])

In [42]:
mat[0:2]

array([[0.17682077, 0.38666533, 0.73258622, 0.42644438],
       [0.54252846, 0.62054132, 0.56371885, 0.97001606]])

You should notice the difference between the two slicing approaches below:

In [43]:
mat[:, 1:2]

array([[0.38666533],
       [0.62054132],
       [0.87853951]])

In [44]:
mat[:, 1]

array([0.38666533, 0.62054132, 0.87853951])