In [1]:
import numpy as np

# Part II: Basic Operations

---

The NumPy operations are placed into three groups of:

1. Array with Array
2. Array with Scalars
3. Universal Array Functions

I explain examples for each as follows.

## 1. Array with Array

We can have element-wise array-array operations as follows:

In [2]:
arr_1 = np.arange(10, 20)
arr_2 = np.arange(20, 30)
print(arr_1, arr_2)

[10 11 12 13 14 15 16 17 18 19] [20 21 22 23 24 25 26 27 28 29]


In [3]:
sum_ew = arr_1 + arr_2
sub_ew = arr_1 - arr_2
mul_ew = arr_1 * arr_2
div_ew = arr_1 / arr_2
mod_ew = arr_1 % arr_2

In [4]:
print('Sum: {}\nSub: {}\nMul: {}\nDiv: {}\nMod: {}'.format(sum_ew, sub_ew, 
                                                           mul_ew, np.round(div_ew, 3), 
                                                           mod_ew))

Sum: [30 32 34 36 38 40 42 44 46 48]
Sub: [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
Mul: [200 231 264 299 336 375 416 459 504 551]
Div: [0.5   0.524 0.545 0.565 0.583 0.6   0.615 0.63  0.643 0.655]
Mod: [10 11 12 13 14 15 16 17 18 19]


## 2. Array with Scalars

We can have mathematical operations between NumPy arrays and scalars. For example, if we add a NumPy array with a scalar, the value of that scalar is added to every elements of the array.

In [5]:
arr = np.arange(10, 20)

In [6]:
arr + 100

array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [7]:
arr - 2

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [8]:
arr ** 2

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361])

## 3. Universal Function

Universal functions perform a specific operation on every elements of arrays. Here, we look at common ones. Please note that a complete list of universal functions is available at: https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html

In [9]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The number of dimensions:

In [10]:
arr.ndim

1

Retrieving the indices of non-zero elements:

In [11]:
arr.nonzero()

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)

The data type of elements inside an array:

In [12]:
arr.dtype

dtype('int64')

The size of every element inside an array:

In [13]:
arr.itemsize

8

The total number of elements in an array:

In [14]:
arr.size

10

The shape of an array:

In [15]:
arr.shape

(10,)

**Other Functions:**

In [16]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

We can modify a sequence in-place by shuffling its contents as follows:

In [18]:
np.random.shuffle(arr)
arr

array([6, 8, 4, 5, 2, 7, 9, 0, 3, 1])

In [19]:
print('min: {}, argmin: {}'.format(np.min(arr), np.argmin(arr)))
print('max: {}, argmax: {}'.format(np.max(arr), np.argmax(arr)))

min: 0, argmin: 7
max: 9, argmax: 6


In [20]:
print('mean: {}, median: {}, std: {}.'.format(np.mean(arr), np.median(arr), np.std(arr)))

mean: 4.5, median: 4.5, std: 2.8722813232690143.


In [21]:
np.sin(arr)

array([-0.2794155 ,  0.98935825, -0.7568025 , -0.95892427,  0.90929743,
        0.6569866 ,  0.41211849,  0.        ,  0.14112001,  0.84147098])

In [22]:
np.sum(arr)

45

In [23]:
np.round(np.sqrt(arr), 2)

array([2.45, 2.83, 2.  , 2.24, 1.41, 2.65, 3.  , 0.  , 1.73, 1.  ])

### Matrix Operations

In [24]:
mat = np.arange(1, 11).reshape(2, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
mat.ndim

2

In [26]:
mat.size

10

In [27]:
mat.shape

(2, 5)

We can flatten a matrix by the ravel() or the flatten() functions:

In [28]:
mat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
print('Row: {}'.format(mat.flatten(order='C')))
print('Col: {}'.format(mat.flatten(order='F')))

Row: [ 1  2  3  4  5  6  7  8  9 10]
Col: [ 1  6  2  7  3  8  4  9  5 10]


In [30]:
print('sum: by column is {}, by row is {}.'.format(mat.sum(axis=0), mat.sum(axis=1)))

sum: by column is [ 7  9 11 13 15], by row is [15 40].


In [31]:
print('mean: by column is {}, by row is {}.'.format(mat.mean(axis=0), mat.mean(axis=1)))

mean: by column is [3.5 4.5 5.5 6.5 7.5], by row is [3. 8.].


The matrix transpose operation can be done in two forms:

In [32]:
mat.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [33]:
mat.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

#### Matrix Inversion

Please recall that a matrix should have a square shape to be inversable.

In [34]:
mat = np.random.rand(3, 3)
mat

array([[0.88030629, 0.42698222, 0.67847013],
       [0.30875544, 0.03013604, 0.71928752],
       [0.2196726 , 0.78470931, 0.63863958]])

In [35]:
mat_inv = np.linalg.pinv(mat)
mat_inv

array([[ 1.61887989, -0.77119781, -0.85126055],
       [ 0.1163287 , -1.2268333 ,  1.25817497],
       [-0.69978089,  1.77270338,  0.31269125]])

In [36]:
np.matmul(mat, mat_inv).round()

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [-0.,  0.,  1.]])

## 4. Handling Exceptions

NumPy automatically handles the exceptions, for example, for `0/0` it outputs `nan`, and for `1/0` it outputs `inf`.

In [37]:
arr = np.arange(0, 6)

In [38]:
arr / arr

/home/ali/python/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.])

In [39]:
1 / arr

/home/ali/python/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       ])