In [1]:
import numpy as np

# Part III: Advanced Operations

---

## 1. Stacking

Numpy lets us stack N-D arrays vertically or horizontally.

In [2]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_1

array([[1, 2],
       [3, 4]])

In [3]:
arr_2 = np.array([[5, 6], [8, 5]])
arr_2

array([[5, 6],
       [8, 5]])

**Vertical Stacking**

In [4]:
print(np.vstack((arr_1, arr_2)))

[[1 2]
 [3 4]
 [5 6]
 [8 5]]


**Horizontal Stacking**

In [5]:
print(np.hstack((arr_1, arr_2)))

[[1 2 5 6]
 [3 4 8 5]]


## 2. Splitting

In [6]:
arr = np.arange(30).reshape(2, 15)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**Vertical Splitting**

In [7]:
v_splits = np.vsplit(arr, 2)

for i, split in enumerate(v_splits):
    print('Split {}: \n{}.\n'.format(i + 1, split))

Split 1: 
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]].

Split 2: 
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]].



**Horizontal Splitting**

In [8]:
h_splits = np.hsplit(arr, 5)

for i, split in enumerate(h_splits):
    print('Split {}: \n{}.\n'.format(i + 1, split))

Split 1: 
[[ 0  1  2]
 [15 16 17]].

Split 2: 
[[ 3  4  5]
 [18 19 20]].

Split 3: 
[[ 6  7  8]
 [21 22 23]].

Split 4: 
[[ 9 10 11]
 [24 25 26]].

Split 5: 
[[12 13 14]
 [27 28 29]].



# Part IV: Iteration

In [9]:
arr = np.arange(11, 23).reshape(3, 4)
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [10]:
for row in arr:
    for cell in row:
        print(cell, end=' ')

11 12 13 14 15 16 17 18 19 20 21 22 

In [11]:
for cell in arr.flatten():
    print(cell, end=' ')

11 12 13 14 15 16 17 18 19 20 21 22 

## Iteration by nditr

**nditr** is an efficient multi-dimensional iterator object that iterates over arrays: <br/>
https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.nditer.html

In [12]:
arr = np.arange(11, 23).reshape(3, 4)
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [13]:
for cell in np.nditer(arr, order='C'):
    print(cell, end=' ')

11 12 13 14 15 16 17 18 19 20 21 22 

In [14]:
for cell in np.nditer(arr, order='F'):
    print(cell, end=' ')

11 15 19 12 16 20 13 17 21 14 18 22 

In [15]:
for column in np.nditer(arr, order='F', flags=['external_loop']):
    print(column)

[11 15 19]
[12 16 20]
[13 17 21]
[14 18 22]


In [16]:
for row in np.nditer(arr, op_flags=['readwrite']):
    row[...] = row + 100

print(arr)

[[111 112 113 114]
 [115 116 117 118]
 [119 120 121 122]]


**Iteration through two arrays:**

In [17]:
arr = np.arange(11, 23).reshape(3, 4)
arr

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [18]:
arr_ = np.arange(101, 113).reshape(3, 4)
arr_

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

In [19]:
for x, y in np.nditer((arr, arr_), order='F'):
    print(x, y)

11 101
15 105
19 109
12 102
16 106
20 110
13 103
17 107
21 111
14 104
18 108
22 112


---

## Conditional Selection

Let's create a matrix as follows:

In [20]:
mat = np.random.rand(3, 5)
mat

array([[0.82517021, 0.81869208, 0.73753419, 0.63238836, 0.55987403],
       [0.11663931, 0.83688899, 0.83154971, 0.09520793, 0.74959178],
       [0.52767112, 0.8018866 , 0.68076152, 0.07174351, 0.42902689]])

To see if a condition is met, we can do:

In [21]:
mat_b = mat > 0.5
mat_b

array([[ True,  True,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True,  True,  True, False, False]])

We can then retrieve the elements which meet the foregoing condition as:

In [22]:
mat[mat_b]

array([0.82517021, 0.81869208, 0.73753419, 0.63238836, 0.55987403,
       0.83688899, 0.83154971, 0.74959178, 0.52767112, 0.8018866 ,
       0.68076152])

In one shot, we can have:

In [23]:
mat[mat > 0.5]

array([0.82517021, 0.81869208, 0.73753419, 0.63238836, 0.55987403,
       0.83688899, 0.83154971, 0.74959178, 0.52767112, 0.8018866 ,
       0.68076152])

We can also modify the elements of the matrix as below:

In [24]:
mat[mat > 0.5] = 2
mat

array([[2.        , 2.        , 2.        , 2.        , 2.        ],
       [0.11663931, 2.        , 2.        , 0.09520793, 2.        ],
       [2.        , 2.        , 2.        , 0.07174351, 0.42902689]])